name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') &&
         contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude') &&
         contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association)) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude') &&
         contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.review.author_association)) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude') &&
         contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.issue.author_association))
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write          # Allow git operations (commit, push)
      pull-requests: write     # Allow PR creation and updates
      issues: write           # Allow issue updates
      id-token: write         # Keep existing OIDC support
      actions: read           # Allow reading workflow runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # Full history for git operations
          token: ${{ github.token }}  # Ensure token is available

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'    # Match your project's Node version
          cache: 'npm'          # Cache npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Ensure token is available to Claude